### ISSUE TITLE
Does this support Rackspace CloudFiles via the swift api?

### ISSUE THREAD

**Issue by ammonkc** [nimbusoftltd/flysystem-openstack-swift#12]
Does this package support rackspace cloudfile? I believe Rackspace cloudfiles is based on openstack swift. I seem to can't figure out how to authenticate it with rackspace cloud's Identity v2.0.

**Comment by DSpeichert** [comment]
@ammonkc Try http://flysystem.thephpleague.com/docs/adapter/rackspace/ instead.

**Comment by ammonkc** [comment]
Thanks for the suggestion, but I was trying to find an alternative to league/flysystem-rackspace since it still uses the guzzle/guzzle 3.x package which is abandoned.

**Comment by mzur** [comment]
Have you seen [this](https://php-openstack-sdk.readthedocs.io/en/latest/services/identity/v2/authentication.html) in the OpenStack SDK docs? It should be the correct way to authenticate with Rackspace.

**Comment by chrisnharvey** [comment]
Thanks @mzur
