### ISSUE TITLE
Optimising upload

### ISSUE THREAD

**Issue by sausin** [nimbusoftltd/flysystem-openstack-swift#2]
Hi!

This query is specifically for OVH but I suppose this would probably apply for other providers.

As described [here](https://www.ovh.com/us/g1951.optimised_method_uploading_files_object_storage) on OVH support page, it's possible to upload a file in multiple pieces.

Is this possible to implement? If it's already implemented, how can this be specified?

Thanks!
Saurabh

**Comment by anhphamt** [comment]
Hi

You can follow this sample and update your code, in the write function of SwiftAdapter.php
https://github.com/php-opencloud/openstack/blob/master/samples/object_store/v1/objects/create_large_object.php

I also made a Pull Request and waiting for approval from the owner of this repo.

Thank you. 
Anh Pham

**Comment by sausin** [comment]
@anhphamt Thanks a bunch! I've implemented your solution. Though not tested it yet, I see that it should work just fine :+1:
