### ISSUE TITLE
Does this package have a future?

### ISSUE THREAD

**Issue by mzur** [nimbusoftltd/flysystem-openstack-swift#36]
I'm currently unable to update the PHP dependencies of one of my applications because [`php-opencloud/openstack`](https://github.com/php-opencloud/openstack) is incompatible with the most recent version of Laravel 9. It does also not support PHP 8.1 (although it worked fine for me so far). Their repository is inactive with no commits for 1.5 years.

For these reasons, I'm probably forced to switch to S3 with my application and I can no longer use the Swift API.

So does this package have a future? If `php-opencloud/openstack` is no longer maintained and incompatible with other packages/new PHP versions, I see no way to maintain this package as well.

**Comment by sausin** [comment]
Seems like game over on openstack. We had a good run while it lasted though. Thanks for maintaining this package in the meanwhile @mzur 🍾

**Comment by k0ka** [comment]
Well, the openstack is still alive. I was able to install this package with Laravel 9. While `php-opencloud/openstack` is not maintained it is still working properly. They support php 8.x so it should be fine till php 9 (which is not announced yet).

**Comment by mzur** [comment]
> I was able to install this package with Laravel 9.

@k0ka With the most recent version? Laravel >=9.51 requires `guzzlehttp/uri-template:^1.0` which conflicts with `guzzlehttp/uri-template:0.2` from `php-opencloud/openstack`.

This can probably be fixed easily but the last PR was merged in 2021 and I don't want to maintain a fork of `php-opencloud/openstack`. It's too easy to just switch to S3.

**Comment by k0ka** [comment]
I became maintainer of [php-opencloud/openstack](https://github.com/php-opencloud/openstack) and released version which supports `guzzlehttp/uri-template:^1.0`

**Comment by mzur** [comment]
Nice! :+1:
