### ISSUE TITLE
Broken deleteDir

### ISSUE THREAD

**Issue by Y0lk** [nimbusoftltd/flysystem-openstack-swift#4]
I'm not sure if this is a problem with the OpenStack SDK or the adapter, but deleteDir ends up throwing an exception ""containerName" is a required option, but it was not provided".

The adapter is very simple, it just uses **listObjects** on the container with a prefix, and then calls the **delete** method on each object returned by **listObjects**. From what I understand, the objects returned by **listObjects** do not have their **containerName** property set on them, which is why we get the error when delete is called on them.

So the deleteDir method can easily be fixed by specifying the container on each object like this:
```php
public function deleteDir($dirname)
    {
        $objects = $this->container->listObjects([
            'prefix' => $this->applyPathPrefix($dirname)
        ]);

        try {
            foreach ($objects as $object) {
                $object->containerName = $this->container->name; //The fix
                $object->delete();
            }
        } catch (BadResponseError $e) {
            return false;
        }

        return true;
    }
```

I'm just not sure if it was intended to be like this in the SDK or if it's a bug. 
Here's a PR with the fix for now.

**Comment by chrisnharvey** [comment]
Many thanks for reporting and fixing this. Closing this issue now.

**Comment by DSpeichert** [comment]
Please release package update, the only option to get this fix is by using dev-master (via composer).
